version: 2

sources:
  - name: trips_data_all
    description: >
      Data Warehouse tables in BigQuery.
    database: dataanalyticscourse-327913
    schema: trips_data_all
    tables:
      - name: yellow_tripdata
      - name: yellow_tripdata_external_table