taxi_rides_ny:
  outputs:
    dev:
      dataset: trips_data_all
      fixed_retries: 1
      keyfile: /.google/credentials/google_credentials.json
      location: EU
      method: service-account
      priority: interactive
      project: dataanalyticscourse-327913
      threads: 4
      timeout_seconds: 300
      type: bigquery
  target: dev
